### PR TITLE
Connection wording

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Comment by esune** [comment]
@swcurran it appears that this PR got stale and now cannot be merged. The remote was deleted so I am wondering how you would like to proceed.

**Comment by swcurran** [comment]
Looks like the changes can be recreated...I'll try again.

**Comment by esune** [comment]
Thanks! I didn't have merge rights in the past, but I can now act more swiftly 😉

**Comment by esune** [comment]
@swcurran is this still needing to be updated, or can it be closed and dismissed? If it needs updating, can you push the required changes?

**Comment by swcurran** [comment]
It's still on my list :-(.  #fail

**Pull request closed without merging**
